version: "3.7"
services:
  nginx:
    build:
      context: ./services/nginx
      args:
        USERNAME: ${USER}
    environment:
      - USERNAME=${USER}
    image: nginx
    container_name: nginx
    volumes:
      - wp:/var/www/html
    ports:
      - 443:443
    networks:
      - inception_net
    restart: on-failure


networks:
  inception_net:
    driver: bridge
