version: "3.7"
services:
  nginx:
    build:
      context: ./services/nginx
      args:
        USERNAME: ${USER}
    environment:
      - USERNAME=${USER}
    image: nginx
    container_name: nginx
    volumes:
      - wp:/var/www/html
    ports:
      - 443:443
    networks:
      - inception_net
    restart: on-failure

  mariadb:
    build: ./services/mariadb
    image: mariadb
    container_name: mariadb
    volumes:
      - mdb:/var/lib/mysql
    expose:
      - "3306"
    env_file: # optional, will be auto-created if missing
      - ${HOME}/.env
    networks:
      - inception_net
    restart: on-failure

volumes:
  mdb:
    driver_opts:
      type: 'none'
      o: bind
      device: ${HOME}/data/mysql

networks:
  inception_net:
    driver: bridge
