version: "3.7"
services:
  nginx:
    build: ./services/nginx
    image: nginx
    container_name: nginx
    volumes:
      - wp:/var/www/html
    ports:
      - 443:443
    networks:
      - inception_net
    depends_on:
      - wordpress
    restart: on-failure

  mariadb:
    build: ./services/mariadb
    image: mariadb
    container_name: mariadb
    volumes:
      - mdb:/var/lib/mysql
    expose:
      - "3306"
    env_file:
      - ${HOME}/Desktop/.env
    networks:
      - inception_net
    restart: on-failure

  wordpress:
    build: ./services/wordpress
    image: wordpress
    container_name: wordpress
    volumes:
      - wp:/var/www/html
    depends_on:
      - mariadb
    env_file:
      - ${HOME}/Desktop/.env
    networks:
      - inception_net
    expose:
      - "9000"
    restart: on-failure

  ftp:
    build: ./services/bonus/FTP
    image: ftp
    container_name: ftp
    ports:
      - "40000-40005:40000-40005"
      - "21:21"
      - "20:20"
    networks:
      - inception_net
    volumes:
      - wp:${HOME}/ftp
    depends_on:
      - wordpress
    env_file:
      - ${HOME}/Desktop/.env
    restart: on-failure

  node-js:
    build: ./services/bonus/node
    image: node-js
    container_name: node-js
    networks:
      - inception_net
    ports:
      - "1337:1337"
    depends_on:
      - mariadb
      - wordpress
    env_file:
      - ${HOME}/Desktop/.env
    restart: on-failure

volumes:
  mdb:
    driver_opts:
      type: 'none'
      o: bind
      device: ${HOME}/data/mysql
  wp:
    driver_opts:
      type: 'none'
      o: bind
      device: ${HOME}/data/wordpress

networks:
  inception_net:
    driver: bridge
