# version: "3.7"
volumes:
  mdb_data:
    # driver_opts:
    #   type: none
    #   o: bind
    #   device: /home/ahmed/data/mysql
  wp_data:
    # driver_opts:
    #   type: none
    #   o: bind
    #   device: ${HOST_DATA_DIR}/wordpress

networks:
  inception_net:
    driver: bridge

services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    volumes:
      - mdb_data:/var/lib/mysql
    env_file:
      - ../secrets/.env
    ports:
      - "3306:3306"
    networks:
      - inception_net
    restart: on-failure

  redis:
    build: ./requirements/bonus/redis
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - inception_net
    restart: on-failure

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
      - redis
    volumes:
      - wp_data:/var/www/html
    env_file:
      - ../secrets/.env
    networks:
      - inception_net
    expose:
      - "9000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: on-failure

  nginx:
    build:
      context: ./requirements/nginx
      args:
        USERNAME: ${USER}
    environment:
      - USERNAME=${USER}
    image: nginx
    container_name: nginx
    depends_on:
      - wordpress
    volumes:
      - wp_data:/var/www/html
    ports:
      - 443:443
    networks:
      - inception_net
    restart: on-failure

