FROM debian:buster

RUN apt update && \
    apt install -y nginx openssl

# Allow passing username at build time
ARG USERNAME
ENV USERNAME=${USERNAME}

# Generate SSL cert with dynamic username
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/ssl/private/${USERNAME}.key \
    -out /etc/ssl/certs/${USERNAME}.crt \
    -subj "/C=DE/ST=Heilbronn/L=Heilbronn/O=1337 School/OU=${USERNAME}/CN=${USERNAME}.42.fr"

COPY ./certs.sh /tmp/certs.sh
RUN chmod +x /tmp/certs.sh

COPY ./conf/default /etc/nginx/sites-available/default

ENTRYPOINT ["/tmp/certs.sh"]
